### ISSUE TITLE
Thread sleep efficiency

### ISSUE THREAD

**Issue by Nodiink** [ViniciusAlberkovics/VSGitAutoFetch#1]
As per performance efficiency ([example](https://stackoverflow.com/questions/45007614/alternative-to-thread-sleep-in-a-while-loop)), I suggest to change `Thread.Sleep` with `await Task.Delay` in AuthFetch.cs, line 120.

**Comment by ViniciusAlberkovics** [comment]
Fixed in version 1.1.5
