### ISSUE TITLE
VS2022 Support

### ISSUE THREAD

**Issue by KoalaBear84** [ViniciusAlberkovics/VSGitAutoFetch#2]
Please update it to support VS2022.

Thanks in advance!

**Comment by leprox43** [comment]
@KoalaBear84 
https://marketplace.visualstudio.com/items?itemName=leprox43.GitAutoFetchVS2022

**Comment by KoalaBear84** [comment]
Thanks @Leprox43 !

**Comment by ViniciusAlberkovics** [comment]
Fixed in version 1.1.5

**Comment by ryanbuening** [comment]
When I try to configure fetching, nothing happens. Am I missing something?

![autofetch](https://user-images.githubusercontent.com/812974/157452384-249c0fbe-c301-4f5d-9e2d-9f2425864004.gif)

**Comment by ryanbuening** [comment]
Disregard my previous comment. `VsGitAutoFetch.json` is now opening in Notepad when I click "Configure Fetching". I'm not sure what changed 🤷‍♂️

**Comment by charlesroddie** [comment]
> VsGitAutoFetch.json is now opening in Notepad when I click "Configure Fetching". I'm not sure what changed 🤷‍♂️

Yes found Git Autofetch on VS2022 completely ineffective by default (never fetching for long intervals).

Clicking on "Configure Fetching" gives:

```
{
  "UserTime": 0
}
```

The documentation https://marketplace.visualstudio.com/items?itemName=ZweiDeveloper.gitAutoFetch
has as a top level description
```
Git AutoFetch in minutes, default value is 5 minutes.
```
This is not necessarily a description of `UserTime` but I'm going to try assuming that UserTime is an integer describing a number of minutes whose default value should have been 5 but in practice defaults to 0 and see what happens.
